<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 2.11.6 setup script by Michal Čihař <michal@cihar.com>
 * Version: $Id: setup.php 10748 2007-10-10 07:30:59Z cybot_tm $
 * Date: Thu, 12 Jun 2008 19:23:27 GMT
 */

/* Servers configuration */
$i = 0;

/* Server localhost (http) [1] */
$i++;
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['controluser'] = 'topicos';
$cfg['Servers'][$i]['controlpass'] = 't0p1c0s';
$cfg['Servers'][$i]['auth_type'] = 'http';

/* End of servers configuration */

?>
